version: 0.2
phases:
pre_build:
commands:
- dotnet restore
build:
commands:
- dotnet publish -o output
- mkdir build
- cp -R output build/output
- cp Dockerfile build/Dockerfile
artifacts:
files:
- '**/*'
base-directory: build